---
title: "project"
author: "name"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  prettydoc::html_pretty:
    theme: cayman
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# set working directory to the location of the script
knitr::opts_knit$set(root.dir = getwd())
setwd(dirname(rstudioapi::getSourceEditorContext()$path))

# load packages
library(knitr)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(patchwork)
```

# print session info (package versions)
```{r session_info}

# print versions
sessionInfo()

```

# read data
``` {r read_data}
# read as a tibble
data <- read_csv("data/data.csv")

# print the dimensions of the table for reference
dim(data)
```

# make a plot and print it so we can see it in the knitR document
``` {r plot_data}
plot <- data %>% 
  ggplot(aes(x=var1, y=var2)) + 
  geom_point()

plot
```

# save the plot to PDF and PNG
```{r output_figs}

# store figure files in a '/figs' subdir to keep things clean

ggsave(height=6, width=9, file="figs/fig1.pdf")
ggsave(height=6, width=9, file="figs/fig1.png")

```

# make a table and write it to CSV for reference
```{r make_and_print_table}

# create table
table1 <- data %>% group_by(var1) %>% count()

# print table in human redable format
table1 %>% kable()

# write table to file
write.csv(table1, file="tables/table1.csv", row.names=F)

```
